### ISSUE TITLE
Replace our custom Android lib (using ARCore) by Sceneform (and get the Android impl on par with iOS)

### ISSUE THREAD

**Issue by EddyVerbruggen** [EddyVerbruggen/nativescript-ar#37]
[Sceneform](https://developers.google.com/ar/develop/java/sceneform/) is a relatively new abstraction layer on top of ARCore. It doesn't require (plugin) developers to directly interact with OpenGL, which I needed to do previously (hence the embedded custom native library I created).

This hampered progress enormously because of the long development-build-test cycle it caused.

With Sceneform the Android API's are a lot like the iOS ARKit API's so let's use Sceneform and then get the Android implementation on par with iOS.

### Generic tasks:
- [x] Add Sceneform
- [x] Remove our custom lib
- [x] Bump demo to NativeScript 6

### Port iOS features to Android
- [x] World tracking
- [x] Scaffolding for placing objects in the 3D world
- [x] Adding a box
- [x] Adding a sphere (thanks, @nickolanack! #38)
- [x] Adding a tube / cylinder (see #40)
- [x] Face detection/tracking (partly done)
- [x] Image detection/tracking
- [x] Gesture support
- [x] Material support (we only support colors at the moment)

### More demos
- [x] Try to replicate the [Android Solar system demo](https://github.com/google-ar/sceneform-android-sdk/tree/master/samples/solarsystem) for iOS and Android in NativeScript. (implemented in #41)
- [x] Try to replicate the [Android Augmented Image demo](https://github.com/google-ar/sceneform-android-sdk/tree/master/samples/augmentedimage) for iOS and Android in NativeScript. (implemented in #62)
- [x] Add an IKEA-like demo, but for Pokémon (implemented in #70)
- [x] Try to replicate the [Android Augmented Faces demo](https://github.com/google-ar/sceneform-android-sdk/tree/master/samples/augmentedfaces), or something custom like trying different pairs of spectacles 👓🕶(implemented in #72).
- [ ] Possibly one or more of the other [Android demos](https://developers.google.com/ar/develop/java/sceneform/samples).

**Comment by EddyVerbruggen** [comment]
Also, let's bump the demo to NativeScript 6.

**Comment by nickolanack** [comment]
awesome work!!!
- I've updated my fork with this, and implemented the addSphere method. 

I was also wondering if it makes sense to use a single origin anchor for new items (I believe it is more efficient to share anchors if possible) unless they are attached to a surface anchor... thoughts?

I was hoping to support options.parentNode for add* which would make sense in the solar system example for instance (https://developers.google.com/ar/develop/java/sceneform/samples)

I'd also like to add support for a new node type 'ARUIView'  or something like that which could render nativescript ui components in a panel in 3D i've successfully done this in android and it should be possible in ios

**Comment by EddyVerbruggen** [comment]
Hey @nickolanack, really happy with your contributions and ideas!

Please go ahead and try a few things, and once you're happy feel free to create a PR from your fork or push directly to master (make sure you don't break backward compatibility for iOS).

Regarding an ARUIView: I was thinking the same and experimented with it on Android last weekend. It seemed to work, but was a bit hacky. And I would be really interested if something similar is possible on iOS.
My approach was to define some markup [like this](https://github.com/EddyVerbruggen/nativescript-ar/blob/ea5b67004615d4a5d05aca2e755b1530cd1999c3/demo/app/main-page.xml#L5-L8) and add it to the AR scene [like this](https://github.com/EddyVerbruggen/nativescript-ar/blob/ea5b67004615d4a5d05aca2e755b1530cd1999c3/src/ar.android.ts#L216-L230). That switch actually fires the `onTap="tapp"` method when toggled in AR so as a PoC it works great, but code-wise it's a bit hacky.

**Comment by nickolanack** [comment]
I've also created branches for addTube (although it is just a cylinder) 
and a branch for addUIView which will display nativescript ui content although at the moment just Hello World text

I don't want to PR any more until you've had a chance to review the current PR and make sure I'm not going off in the wrong direction...

I also need to get my hands on an iphone to work on addUIView for ios

**Comment by EddyVerbruggen** [comment]
This is now mostly done, with many thanks to @nickolanack!

Not everything is perfect yet, but it's so much better than before. It needs more testing and maybe more demos (and certainly documentation) - I'm aiming for a 1.0.0 release somewhere next month.
